version: "1"
services:
  - type: web
    name: strongs-api
    runtime: node
    repo: https://github.com/wsgutnik/app-biblia-react
    branch: main
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: "18"
