# Exported from Render on 2025-12-12T21:04:33Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: app-biblia-react
      runtime: node
      repo: https://github.com/wsgutnik/app-biblia-react
      plan: free
      region: oregon
      buildCommand: npm install; npm run build
      startCommand: yarn start
      autoDeployTrigger: commit
      rootDir: server
