export const BOOKS = [
    { num: 1, abbrev: "gn", name_pt: "Gênesis", name_en: "Genesis", name_es: "Génesis", chapters: 50 },
    { num: 2, abbrev: "ex", name_pt: "Êxodo", name_en: "Exodus", name_es: "Éxodo", chapters: 40 },
    { num: 3, abbrev: "lv", name_pt: "Levítico", name_en: "Leviticus", name_es: "Levítico", chapters: 27 },
    { num: 4, abbrev: "nm", name_pt: "Números", name_en: "Numbers", name_es: "Números", chapters: 36 },
    { num: 5, abbrev: "dt", name_pt: "Deuteronômio", name_en: "Deuteronomy", name_es: "Deuteronomio", chapters: 34 },
    { num: 6, abbrev: "js", name_pt: "Josué", name_en: "Joshua", name_es: "Josué", chapters: 24 },
    { num: 7, abbrev: "jz", name_pt: "Juízes", name_en: "Judges", name_es: "Jueces", chapters: 21 },
    { num: 8, abbrev: "rt", name_pt: "Rute", name_en: "Ruth", name_es: "Rut", chapters: 4 },
    { num: 9, abbrev: "1sm", name_pt: "1º Samuel", name_en: "1 Samuel", name_es: "1 Samuel", chapters: 31 },
    { num: 10, abbrev: "2sm", name_pt: "2º Samuel", name_en: "2 Samuel", name_es: "2 Samuel", chapters: 24 },
    { num: 11, abbrev: "1rs", name_pt: "1º Reis", name_en: "1 Kings", name_es: "1 Reyes", chapters: 22 },
    { num: 12, abbrev: "2rs", name_pt: "2º Reis", name_en: "2 Kings", name_es: "2 Reyes", chapters: 25 },
    { num: 13, abbrev: "1cr", name_pt: "1º Crônicas", name_en: "1 Chronicles", name_es: "1 Crónicas", chapters: 29 },
    { num: 14, abbrev: "2cr", name_pt: "2º Crônicas", name_en: "2 Chronicles", name_es: "2 Crónicas", chapters: 36 },
    { num: 15, abbrev: "ed", name_pt: "Esdras", name_en: "Ezra", name_es: "Esdras", chapters: 10 },
    { num: 16, abbrev: "ne", name_pt: "Neemias", name_en: "Nehemiah", name_es: "Nehemías", chapters: 13 },
    { num: 17, abbrev: "et", name_pt: "Ester", name_en: "Esther", name_es: "Ester", chapters: 10 },
    { num: 18, abbrev: "job", name_pt: "Jó", name_en: "Job", name_es: "Job", chapters: 42 },
    { num: 19, abbrev: "sl", name_pt: "Salmos", name_en: "Psalms", name_es: "Salmos", chapters: 150 },
    { num: 20, abbrev: "pv", name_pt: "Provérbios", name_en: "Proverbs", name_es: "Proverbios", chapters: 31 },
    { num: 21, abbrev: "ec", name_pt: "Eclesiastes", name_en: "Ecclesiastes", name_es: "Eclesiastés", chapters: 12 },
    { num: 22, abbrev: "ct", name_pt: "Cânticos", name_en: "Song of Solomon", name_es: "Cantares", chapters: 8 },
    { num: 23, abbrev: "is", name_pt: "Isaías", name_en: "Isaiah", name_es: "Isaías", chapters: 66 },
    { num: 24, abbrev: "jr", name_pt: "Jeremias", name_en: "Jeremiah", name_es: "Jeremías", chapters: 52 },
    { num: 25, abbrev: "lm", name_pt: "Lamentações", name_en: "Lamentations", name_es: "Lamentaciones", chapters: 5 },
    { num: 26, abbrev: "ez", name_pt: "Ezequiel", name_en: "Ezekiel", name_es: "Ezequiel", chapters: 48 },
    { num: 27, abbrev: "dn", name_pt: "Daniel", name_en: "Daniel", name_es: "Daniel", chapters: 12 },
    { num: 28, abbrev: "os", name_pt: "Oséias", name_en: "Hosea", name_es: "Oseas", chapters: 14 },
    { num: 29, abbrev: "jl", name_pt: "Joel", name_en: "Joel", name_es: "Joel", chapters: 3 },
    { num: 30, abbrev: "am", name_pt: "Amós", name_en: "Amos", name_es: "Amós", chapters: 9 },
    { num: 31, abbrev: "ob", name_pt: "Obadias", name_en: "Obadiah", name_es: "Abdías", chapters: 1 },
    { num: 32, abbrev: "jn", name_pt: "Jonas", name_en: "Jonah", name_es: "Jonás", chapters: 4 },
    { num: 33, abbrev: "mq", name_pt: "Miquéias", name_en: "Micah", name_es: "Miqueas", chapters: 7 },
    { num: 34, abbrev: "na", name_pt: "Naum", name_en: "Nahum", name_es: "Nahúm", chapters: 3 },
    { num: 35, abbrev: "hc", name_pt: "Habacuque", name_en: "Habakkuk", name_es: "Habacuc", chapters: 3 },
    { num: 36, abbrev: "sf", name_pt: "Sofonias", name_en: "Zephaniah", name_es: "Sofonías", chapters: 3 },
    { num: 37, abbrev: "ag", name_pt: "Ageu", name_en: "Haggai", name_es: "Hageo", chapters: 2 },
    { num: 38, abbrev: "zc", name_pt: "Zacarias", name_en: "Zechariah", name_es: "Zacarías", chapters: 14 },
    { num: 39, abbrev: "ml", name_pt: "Malaquias", name_en: "Malachi", name_es: "Malaquías", chapters: 4 },
    { num: 40, abbrev: "mt", name_pt: "Mateus", name_en: "Matthew", name_es: "Mateo", chapters: 28 },
    { num: 41, abbrev: "mc", name_pt: "Marcos", name_en: "Mark", name_es: "Marcos", chapters: 16 },
    { num: 42, abbrev: "lc", name_pt: "Lucas", name_en: "Luke", name_es: "Lucas", chapters: 24 },
    { num: 43, abbrev: "jo", name_pt: "João", name_en: "John", name_es: "Juan", chapters: 21 },
    { num: 44, abbrev: "atos", name_pt: "Atos", name_en: "Acts", name_es: "Hechos", chapters: 28 },
    { num: 45, abbrev: "rm", name_pt: "Romanos", name_en: "Romans", name_es: "Romanos", chapters: 16 },
    { num: 46, abbrev: "1co", name_pt: "1ª Coríntios", name_en: "1 Corinthians", name_es: "1 Corintios", chapters: 16 },
    { num: 47, abbrev: "2co", name_pt: "2ª Coríntios", name_en: "2 Corinthians", name_es: "2 Corintios", chapters: 13 },
    { num: 48, abbrev: "gl", name_pt: "Gálatas", name_en: "Galatians", name_es: "Gálatas", chapters: 6 },
    { num: 49, abbrev: "ef", name_pt: "Efésios", name_en: "Ephesians", name_es: "Efesios", chapters: 6 },
    { num: 50, abbrev: "fp", name_pt: "Filipenses", name_en: "Philippians", name_es: "Filipenses", chapters: 4 },
    { num: 51, abbrev: "cl", name_pt: "Colossenses", name_en: "Colossians", name_es: "Colosenses", chapters: 4 },
    { num: 52, abbrev: "1ts", name_pt: "1ª Tessalonicenses", name_en: "1 Thessalonians", name_es: "1 Tesalonicenses", chapters: 5 },
    { num: 53, abbrev: "2ts", name_pt: "2ª Tessalonicenses", name_en: "2 Thessalonians", name_es: "2 Tesalonicenses", chapters: 3 },
    { num: 54, abbrev: "1tm", name_pt: "1ª Timóteo", name_en: "1 Timothy", name_es: "1 Timoteo", chapters: 6 },
    { num: 55, abbrev: "2tm", name_pt: "2ª Timóteo", name_en: "2 Timothy", name_es: "2 Timoteo", chapters: 4 },
    { num: 56, abbrev: "tt", name_pt: "Tito", name_en: "Titus", name_es: "Tito", chapters: 3 },
    { num: 57, abbrev: "fm", name_pt: "Filemom", name_en: "Philemon", name_es: "Filemón", chapters: 1 },
    { num: 58, abbrev: "hb", name_pt: "Hebreus", name_en: "Hebrews", name_es: "Hebreos", chapters: 13 },
    { num: 59, abbrev: "tg", name_pt: "Tiago", name_en: "James", name_es: "Santiago", chapters: 5 },
    { num: 60, abbrev: "1pe", name_pt: "1ª Pedro", name_en: "1 Peter", name_es: "1 Pedro", chapters: 5 },
    { num: 61, abbrev: "2pe", name_pt: "2ª Pedro", name_en: "2 Peter", name_es: "2 Pedro", chapters: 3 },
    { num: 62, abbrev: "1jo", name_pt: "1ª João", name_en: "1 John", name_es: "1 Juan", chapters: 5 },
    { num: 63, abbrev: "2jo", name_pt: "2ª João", name_en: "2 John", name_es: "2 Juan", chapters: 1 },
    { num: 64, abbrev: "3jo", name_pt: "3ª João", name_en: "3 John", name_es: "3 Juan", chapters: 1 },
    { num: 65, abbrev: "jd", name_pt: "Judas", name_en: "Jude", name_es: "Judas", chapters: 1 },
    { num: 66, abbrev: "ap", name_pt: "Apocalipse", name_en: "Revelation", name_es: "Apocalipsis", chapters: 22 }
];

export const VERSIONS = [
    // Versões em Português
    { id: 'almeida_ra', name: 'Almeida Revista e Atualizada' },
    { id: 'almeida_rc', name: 'Almeida Revista e Corrigida' },
    { id: 'blivre', name: 'Bíblia Livre' },
    // Versões em Inglês
    { id: 'asv', name: 'American Standard Version' },
    { id: 'asvs', name: 'American Standard Version w Strongs' },
    { id: 'bishops', name: 'Bishops Bible' },
    { id: 'coverdale', name: 'Coverdale Bible' },
    { id: 'geneva', name: 'Geneva Bible' },
    { id: 'kjv', name: 'King James Version' },
    { id: 'kjv_strongs', name: 'KJV with Strongs' },
    { id: 'net', name: 'NET Bible®' },
    { id: 'tyndale', name: 'Tyndale Bible' },
    { id: 'web', 'name': 'World English Bible' },
    // NOVAS: Versões em Espanhol
    { id: 'rv_1858', name: 'Reina Valera 1858' },
    { id: 'rv_1909', name: 'Reina Valera 1909' },
    { id: 'rvg', name: 'Reina Valera Gómez' },
    { id: 'sagradas', name: 'Sagradas Escrituras' },
    { id: 'rv_1909_strongs', name: 'Reina Valera 1909 with Strongs' },
];
